# Generated by Django 6.0.3 on 2026-04-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
